name: Release PyCaption on GitHub

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  call-unit-tests-workflow:
    name: Run unit tests
    uses: pbs/pycaption/.github/workflows/main.yml@OCTO-10311-update_test_notifications_to_be_more_verbose
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

  create-release:
    name: Release PyCaption on GitHub
    needs: call-unit-tests-workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create release on GitHub
      run: gh release create ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
