name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      SLACK_CHANNEL_ID:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        id: tests
        # Run tox using the version of Python in `PATH`
        run: tox -e py
        continue-on-error: true

      - name: Add context info to env from junit.xml and coverage.xml files using xpath
        run: |
          apt-get install -y --no-install-recommends libxml-xpath-perl
          export COVERAGE=`xpath -q -e "/coverage/@line-rate * 100" coverage.xml`
          export FAILED_AMOUNT=`xpath -q -e "number(/testsuites/testsuite/@failures)" junit.xml`
          SKIPPED_AMOUNT=`xpath -q -e "number(/testsuites/testsuite/@skipped)" junit.xml`
          export PASSED_AMOUNT=`xpath -q -e "/testsuites/testsuite/@tests - $SKIPPED_AMOUNT - $FAILED_AMOUNT" junit.xml`

      - name: Notify if test FAILED
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-text: ":boom: $FAILED_AMOUNT Pycaption tests failed for Python ${{ matrix.python-version }} covering $COVERAGE% of code on the ${{ github.ref_name }} branch (triggered by ${{ github.actor }})"
          slack-optional-icon_emoji: ":boom:"
        if: steps.tests.outcome == 'failure'

      - name: Mark test failure
        run: exit 1
        if: steps.tests.outcome == 'failure'

      - name: Slack notify tests PASSED
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-text: ":rocket: All ($PASSED_AMOUNT) Pycaption tests passed for Python ${{ matrix.python-version }} covering $COVERAGE% of code on the $GITHUB_REF_NAME branch (triggered by $GITHUB_ACTOR)"
          slack-optional-icon_emoji: ":rocket:"
        if: steps.tests.outcome == 'success'
